name: Main

on:
  schedule:
    #  9:00 in JST
    - cron: "0 0 * * *"

jobs:
  bot:
    name: bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install
      - name: yarn start
        run: yarn start
      - name: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git diff --cached --quiet HEAD || git commit -m "save" && git push
