name: Tweet

on:
  schedule:
    #  12:00(1st day) in JST
    - cron: "0 3 1 * *"

jobs:
  bot:
    name: bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install
      - name: tweet
        run: yarn tweet
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      - name: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git diff --cached --quiet HEAD || git commit -m "save" && git push
